import numpy as np
import sympy as sp
from sympy.matrices.normalforms import hermite_normal_form
from functools import lru_cache
from cytools import Polytope

from .utils import (
    is_primitive
)

def enumerate_nonnegative_solutions(A: np.ndarray, b: np.ndarray):
    A = np.asarray(A, dtype=int)
    b = np.asarray(b, dtype=int)
    m, n = A.shape
    y = np.zeros(n, dtype=int)
    out = []

    def rec(j, residual):
        if j == n:
            if np.all(residual == 0):
                out.append(y.copy())
            return
        col = A[:, j]
        if np.all(col == 0):
            y[j] = 0
            rec(j + 1, residual)
            return
        
        valid_indices = [i for i in range(m) if col[i] > 0]
        if not valid_indices:
            if np.any(residual > 0): return
            ub = 0
        else:
            ub = min((residual[i] // col[i]) for i in valid_indices)

        for val in range(int(ub) + 1):
            new_residual = residual - val * col
            if np.any(new_residual < 0): continue
            y[j] = val
            rec(j + 1, new_residual)
        y[j] = 0

    rec(0, b.copy())
    return out

def _points_fixed_degree(weights, degree):
    """Rekursive Backtracker for Single Systems (x*w = d)"""
    results = []
    n = len(weights)
    def backtrack(i, remaining, current):
        if i == n - 1:
            if weights[i] != 0 and remaining % weights[i] == 0:
                current.append(remaining // weights[i]); results.append(current.copy()); current.pop()
            elif weights[i] == 0 and remaining == 0:
                current.append(0); results.append(current.copy()); current.pop()
            return
        if weights[i] == 0:
            current.append(0); backtrack(i + 1, remaining, current); current.pop()
        else:
            for val in range(remaining // weights[i] + 1):
                current.append(val); backtrack(i + 1, remaining - val * weights[i], current); current.pop()
    backtrack(0, degree, [])
    return results

def points_from_weights(weights, degrees=None):
    """Interface for cytools"""
    w_internal = weights[0] if isinstance(weights[0], (list, tuple, np.ndarray)) else weights
    if degrees is None:
        return Polytope.from_weights(w_internal).points()
    pts = []
    for d in degrees: pts.extend(_points_fixed_degree(w_internal, d))
    return np.unique(np.array(pts), axis=0)

@lru_cache(maxsize=None)
def lattice_points_from_matrix(matrix_tuple):
    A = np.array(matrix_tuple, dtype=int)
    b = A.sum(axis=1)
    pts = enumerate_nonnegative_solutions(A, b)
    return tuple(tuple(int(v) for v in p) for p in pts)

def integer_kernel_basis(M):
    """
    Return an integer basis of ker_Z(M).

    Parameters
    ----------
    M : array-like of shape (m, n), integer

    Returns
    -------
    B : np.ndarray of shape (n, k), integer
        Columns form a Z-basis candidate for the lattice kernel.
        For the small matrices here (typically 2x7), this works well.
    """
    Msp = sp.Matrix(M)
    null_basis = Msp.nullspace()

    if not null_basis:
        n = Msp.shape[1]
        return np.zeros((n, 0), dtype=int)

    cols = []
    for v in null_basis:
        vals = list(v)
        denoms = [sp.denom(x) for x in vals]
        L = lcm_many([int(d) for d in denoms])
        vint = [int(sp.Integer(L) * x) for x in vals]
        g = gcd_many(vint)
        vint = [z // g for z in vint]
        cols.append(vint)

    # Retunr n x k Matrix (Columns are Base Vectors)
    B = np.array(cols, dtype=int).T
    return B

def lattice_coordinates_in_kernel_basis(points, B):
    """
    Express integer kernel points in the basis B.

    Parameters
    ----------
    points : array-like, shape (N, n)
    B      : integer matrix, shape (n, k)

    Returns
    -------
    coords : np.ndarray, shape (N, k), integer
    """
    Bsp = sp.Matrix(B)
    coords = []

    for p in points:
        psp = sp.Matrix([int(v) for v in p])

        sol = Bsp.gauss_jordan_solve(psp)[0]
        sol = [sp.nsimplify(x) for x in sol]

        if not all(val.is_integer for val in sol):
            raise ValueError(f"Point {tuple(p)} is not integral in the chosen kernel basis: {sol}")

        z = [int(val) for val in sol]

        if np.any(np.array(B @ np.array(z, dtype=int)).reshape(-1) != np.array(p, dtype=int)):
            raise ValueError(f"Coordinate reconstruction failed for point {tuple(p)}")

        coords.append(z)

    return np.array(coords, dtype=int)

def lattice_basis_from_point_columns(points):
    """
    Integer basis of the lattice generated by the given points.

    Parameters
    ----------
    points : array-like, shape (N, n)
        Integer points in Z^n.

    Returns
    -------
    B : np.ndarray, shape (n, r)
        Integer basis matrix whose columns generate the same Z-lattice
        as the given points.
    """
    pts = np.array(points, dtype=int)
    if pts.ndim != 2:
        raise ValueError("points must be a 2D array")

    # Columns are the generating lattice vectors
    A = sp.Matrix(pts.T.tolist())   # shape (n, N)

    H = hermite_normal_form(A)

    cols = []
    for j in range(H.cols):
        col = [int(H[i, j]) for i in range(H.rows)]
        if any(v != 0 for v in col):
            cols.append(col)

    if not cols:
        return np.zeros((pts.shape[1], 0), dtype=int)

    B = np.array(cols, dtype=int).T   # shape (n, r)
    return B

def lattice_coordinates_in_basis(points, B):
    """
    Express points in the lattice basis B.

    Parameters
    ----------
    points : array-like, shape (N, n)
    B      : np.ndarray, shape (n, r)

    Returns
    -------
    coords : np.ndarray, shape (N, r), integer
    """
    pts = np.array(points, dtype=int)
    B = np.array(B, dtype=int)

    if B.ndim != 2:
        raise ValueError("B must be a 2D matrix")

    n, r = B.shape
    if pts.shape[1] != n:
        raise ValueError(f"Point dimension {pts.shape[1]} does not match basis ambient dimension {n}")

    Bsp = sp.Matrix(B.tolist())
    coords = []

    for p in pts:
        psp = sp.Matrix([[int(v)] for v in p])   # explicit column vector shape (n,1)
        sol = Bsp.gauss_jordan_solve(psp)[0]
        sol = [sp.nsimplify(x) for x in sol]

        if not all(val.is_integer for val in sol):
            raise ValueError(f"Point {tuple(p)} is not integral in basis: {sol}")

        z = [int(val) for val in sol]

        # sanity check
        recon = B @ np.array(z, dtype=int)
        if np.any(recon != p):
            raise ValueError(f"Reconstruction failed for point {tuple(p)}")

        coords.append(z)

    return np.array(coords, dtype=int)

def reflexive_in_cws_lattice(matrix_tuple):
    M = np.array(matrix_tuple, dtype=int)

    pts = np.array(lattice_points_from_matrix(matrix_tuple), dtype=int)
    if len(pts) == 0:
        return False, None, None

    target = np.ones(M.shape[1], dtype=int)
    shifted_pts = pts - target

    # shifted points must lie in the integer kernel
    if not np.all(M @ shifted_pts.T == 0):
        raise ValueError("Shifted points are not in kernel.")

    # Build the lattice actually generated by the shifted points
    B = lattice_basis_from_point_columns(shifted_pts)
    if B.shape[1] == 0:
        return False, None, None
    pts_lattice = lattice_coordinates_in_basis(shifted_pts, B)
    
    poly = Polytope(pts_lattice)
    ineqs = poly.inequalities()
    normals = np.array(ineqs[:, :-1], dtype=int)
    if not all(is_primitive(n) for n in normals):
        return False, poly, pts_lattice
    
    return poly.is_reflexive(), poly, pts_lattice
