# -*- coding: utf-8 -*-
"""polytopes-playground.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eX76AoomoLJ7qgH_65djB8TlnIS7yLPf
"""

pip install cytools

pip install python-flint

pip install ppl

pip install ortools

pip install qpsolvers

from cytools import Polytope